version: '3.7'

services:
  app:
    image: ruby:3.2.0
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - bundle:/usr/local/bundle
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_REGION: ap-northeast-1
  localstack:
    image: localstack/localstack:0.14.5
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3
      DATA_DIR: /tmp/localstack/data
    volumes:
      - localstack:/tmp/localstack

volumes:
  bundle:
  localstack:
