version: '3.7'

services:
  app:
    build:
      context: ./dockerdev/php
    working_dir: /app
    volumes:
      - ${PWD}/server:/app
    ports:
      - '8000:8000'
    environment:
      APP_NAME: Lumen
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: http://localhost
      APP_TIMEZONE: UTC
      LOG_CHANNEL: stack
      LOG_SLACK_WEBHOOK_URL:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: dummy
      MAIL_PASSWORD: dummy
      MAIL_ENCRYPTION: ''
    command: 'php -S 0.0.0.0:8000 -t public'

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
