version: '3.7'

services:
  app:
    build:
      context: ./dockerdev/php
    working_dir: /app
    volumes:
      - ${PWD}/server:/app
    ports:
      - '8000:8000'
    command: 'php -S 0.0.0.0:8000 -t public'
