version: '3.7'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - vendor:/app/vendor
    command: "php artisan serve --host 0.0.0.0"
    ports:
      - "8000:8000"

volumes:
  vendor:
