version: '3.7'

services:
  firebase:
    build: ./.dockerdev/firebase
    working_dir: /app
    volumes:
      - ${PWD}:/app
    ports:
      - "9001:9001"
      - "9099:9099"
    command: firebase emulators:start
