version: '3.8'

services:
  front:
    image: node:21.6.2
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
  nginx:
    image: nginx:1.25.4
    ports:
      - '8080:80'
    volumes:
      - ${PWD}/public:/usr/share/nginx/html

volumes:
  node_modules:
