version: '3.7'

services:
  app:
    image: ruby:3.2.0
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    command: bundle exec rails s -b 0.0.0.0
    environment:
      S3_REGION: ap-northeast-1
      S3_ACCESS_KEY: dummy
      S3_SECRET_KEY: dummy
      S3_BUCKET: microposts
      S3_ENDPOINT: http://localstack:4566
      S3_ASSET_HOST: http://localhost:4566
  localstack:
    image: localstack/localstack
    ports:
      - '8080:8080'
      - '4566:4566'
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data

volumes:
  bundle:
