version: '3.8'

services:

  rails:
    image: ruby:3.2.2
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    command: bundle exec rails s -b 0.0.0.0

volumes:
  bundle:
