version: '3.7'

services:
  client:
    image: node:14.18.2
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - node_modules:/app/node_modules
    ports:
      - "9000:9000"
    command: yarn run dev

  firebase:
    build: .
    working_dir: /app
    volumes:
      - ${PWD}:/app
    ports:
      - "9001:9001"
      - "9099:9099"
    command: firebase emulators:start

volumes:
  node_modules:
