version: '3'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  app:
    image: ruby:3.2.0
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - redis

volumes:
  bundle:
